### ISSUE TITLE
Needs admin approval when using bot

### ISSUE THREAD

**Issue by barryanderson** [engagesquared/TeamsHistoryManagementApp#3]
After deploying the bot users are prompted with a login when running, which requires admin approval. 

![image](https://user-images.githubusercontent.com/7723995/107028644-c0fcf480-67a5-11eb-973e-4b680771c6cd.png)

Bot API settings are as follows:

![image](https://user-images.githubusercontent.com/7723995/107028786-f1dd2980-67a5-11eb-891b-00de471e5370.png)

Can you advise on the API permissions?

**Comment by engagesquared** [comment]
Thanks for pointing it out, the deployment instruction was outdated. I updated it [here](https://github.com/engagesquared/TeamsHistoryManagementApp/wiki/Deployment-guide#bot-graph-api-app) in the 3rd paragraph. You need to grant admin consent for the app either in the "API permissions" page on the screen below or by logging in to the bot using tenant admin's account and checking "Consent on behalf of your organization".
